# fly.toml app configuration file generated for cron-manager on 2024-04-11T14:24:13-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ananni-cron-manager'
primary_region = 'ams'
swap_size_mb = 512

[[mounts]]
  source = 'data'
  destination = '/data'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
